export const likedListmock = {
  message: '좋아요한 부스 목록 조회 성공',
  data: [
    {
      id: 1,
      user: 1,
      day: ['수요일'],
      time: '10시부터',
      college: '교육관',
      category: '굿즈',
      name: '멋쟁이 사자처럼',
      number: '12',
      thumnail: '../../assets/images/boothdetailpage/defaultthumbnail.svg',
      opened: true,
      hashtag: '#정문',
      notice: 'come come',
      is_liked: true,
      created_at: '2022-08-27 21:47',
      updated_at: '2022-08-28 20:54',
    },
    {
      id: 2,
      user: 2,
      day: ['수요일'],
      time: '11시부터',
      college: '정문',
      category: '굿즈',
      name: '멋쟁이 토마토처럼',
      number: '6',
      thumnail: '../../assets/images/boothdetailpage/defaultthumbnail.svg',
      hashtag: '#살려줘',
      opened: false,
      notice: 'hello',
      is_liked: true,
      created_at: '2022-08-28 19:33',
      updated_at: '2022-08-28 20:54',
    },
  ],
};
